# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Smart-Plugin
version:      1.0.1
version_from: lib/Text/Smart/Plugin.pm
installdirs:  site
requires:
    Template:                      2.06
    Text::Smart:                   1.0.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
